name: Build & Push Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    env:
      VERSION: ''  # Prevent linter warning

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Read version from version.txt
        id: version
        run: |
          VERSION=$(cat version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PAT }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pyflaskdp1:${{ env.VERSION }} .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/pyflaskdp1:${{ env.VERSION }}
